  
name: Build
on: [push]	
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:	
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:	
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
        
      - name: Active Cache
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
               
      - name: Unity - Builder
        uses: game-ci/unity-builder@v1.5
        with:
          unityVersion: 2020.1.0f1
          targetPlatform: StandaloneWindows64
          customParameters: -nographics
          kubeVolumeSize: 10Gi
      
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
