  
name: Build
on: [push]	
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:	
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:	
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
           
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v1.4
        with:
          allowDirtyBuild: true
          unityVersion: 2020.1.0f1
          targetPlatform: StandaloneWindows64
          customParameters: -nographics
      
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
