name: Build
on: [push]	
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:	
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:	
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Active Cache
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
           
                
      - name: Build Unity
        uses: kuler90/build-unity@v1
        with:
          build-target: StandaloneWindows64
          build-path: ./build.exe
      
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
